WIP: Implement CoreOS bdn provision

diff --git a/assets/cloud-config/coreos.yml b/assets/cloud-config/coreos.yml
--- a/assets/cloud-config/coreos.yml
+++ b/assets/cloud-config/coreos.yml
@@ -22,15 +22,25 @@ write_files:
 
       mkfs.ext4 -c -L ROOTVOL -F ${ROOTDEV}
 
-      # tell Foreman about the new rootvol and that the build is complete
-      curl "{{.agent.url}}/cloud-config?{{range $k, $v := .host.selectors}}{{$k}}={{$v}}&{{end}}rootvol=installed" -o cloud.cfg
+      # need to reboot to pick up the new root volume
+      sync
+      fsck -y ${ROOTDEV}
+      if [ $? -ne 0 ]; then
+         echo "FSCK FAILED!  CHECK FILESYTEM MANUALLY!!" > /dev/console
+      else
+         # tell Foreman about the new rootvol and that the build is complete
+         curl -L -H "Content-Type:application/json" -H "Accept:application/json,version=2" -k -u api:c0mcast\! -X POST -d "{\"parameter\":{\"name\":\"rootvol\",\"value\":\"${ROOTDEV}\"}}" https://10.22.81.100/api/hosts/`hostname`/parameters
+         #curl -L -H "Content-Type:application/json" -H "Accept:application/json,version=2" -k -u api:c0mcast\! -X PUT -d "{\"build\":\"false\"}" https://10.22.81.100/api/hosts/`hostname`
 
-      coreos-install -d ${ROOTDEV} -i cloud.cfg
-      udevadm settle
-      systemctl reboot
+         # tell Foreman about the new rootvol and that the build is complete
+         curl "{{.agent.url}}/cloud-config?{{range $k, $v := .host.selectors}}{{$k}}={{$v}}&{{end}}rootvol=installed" -o cloud.cfg 
 
+         coreos-install -d ${ROOTDEV} -i cloud.cfg
+
+         sleep 5
+         reboot
+      fi
 {{ end }}
-
 {{ define "coreos_cloudconfig" }}
 coreos:
 
@@ -39,7 +49,7 @@ coreos:
     reboot-strategy: off
 
   etcd2:
-  {{ if index .host "mstr" }}
+  {{ if eq .host.role "kube-master" }}
     # local master enpoints
     name: {{ .host.mstr }}
     initial-advertise-peer-urls: http://{{.host.ip}}:2380
@@ -48,6 +58,7 @@ coreos:
 
     # cross-origin resource sharing
     cors: "*"
+    # TODO: check that role == "kube-node" here?
   {{ else }}
     proxy: on
   {{ end }}
@@ -57,42 +68,14 @@ coreos:
 
   fleet:
   {{ if index .host "mstr" }}
-    metadata: "role={{.host.role}},kube-master={{.host.mstr}},vlan={{.host.vlan}},vlan-{{.host.vlan}}=true"
+    metadata: "role={{.host.role}},kube-master={{.host.mstr}},vlan={{.host.vlan}},vlan-{{.host.vlan}}=true{{if index .host "fleetadd"}}{{.host.fleetadd}}{{end}}"
   {{ else }}
-    metadata: "role={{.host.role}},vlan={{.host.vlan}},vlan-{{.host.vlan}}=true"
+    metadata: "role={{.host.role}},vlan={{.host.vlan}},vlan-{{.host.vlan}}=true{{if index .host "fleetadd"}}{{.host.fleetadd}}{{end}}"
   {{ end }}
 
   units:
-{{ if index .host "rootvol"}}
-    - name: docker.service
-      drop-ins:
-        - name: 10-docker-opts.conf
-          content: |
-            [Service]
-            # Setting max log size to 10M
-            Environment="DOCKER_OPTS=--log-driver=json-file --log-opt max-size=10m"
-    - name: early-docker.service
-      drop-ins:
-        - name: 10-docker-opts.conf
-          content: |
-            [Service]
-            # Setting max log size to 10M
-            Environment="DOCKER_OPTS=--log-driver=json-file --log-opt max-size=10m"
-    - name: down-interfaces.service
-      command: start
-      content: |
-        [Service]
-        Type=oneshot
-        ExecStart=-/usr/sbin/ethtool -L {{.host.interfaces.first.identifier}} combined 6
-        ExecStart=-/usr/sbin/ethtool -L {{.host.interfaces.second.identifier}} combined 6
-        ExecStart=/usr/bin/bash -c 'ip a show dev po0 | exit'
-        ExecStart=/usr/bin/ip link set {{.host.interfaces.first.identifier}} down
-        ExecStart=/usr/bin/ip addr flush dev {{.host.interfaces.first.identifier}}
-        ExecStart=/usr/bin/ip link set {{.host.interfaces.second.identifier}} down
-        ExecStart=/usr/bin/ip addr flush dev {{.host.interfaces.second.identifier}}
-    - name: systemd-networkd.service
-      command: restart
-{{ else }}
+  #TODO: This looks dirty :(
+{{ if index .host "rootvol" | not}}
     - name: setup.service
       command: start
       content: |
@@ -107,7 +90,20 @@ coreos:
       command: start
     - name: fleet.service
       command: start
-
+    - name: docker.service
+      drop-ins:
+        - name: 10-docker-opts.conf
+          content: |
+            [Service]
+            # Setting max log size to 10M
+            Environment="DOCKER_OPTS=--log-driver=json-file --log-opt max-size=10m"
+    - name: early-docker.service
+      drop-ins:
+        - name: 10-docker-opts.conf
+          content: |
+            [Service]
+            # Setting max log size to 10M
+            Environment="DOCKER_OPTS=--log-driver=json-file --log-opt max-size=10m"
 
 {{ if index .env "ssh_authorized_keys" }}
 ssh_authorized_keys:
@@ -119,54 +115,3 @@ users:
   - name: core
     passwd: {{ .group.root_pass }}
 {{ end }}
-
-write_files:
-  - path: /etc/systemd/network/po0.netdev
-    permissions: 0644
-    owner: root
-    content: |
-      [NetDev]
-      Name=po0
-      Kind=bond
-
-      [Bond]
-      Mode=802.3ad
-      TransmitHashPolicy=layer3+4
-      LACPTransmitRate=fast
-      MIIMonitorSec=1
-  - path: /etc/systemd/network/po0.network
-    permissions: 0644
-    owner: root
-    content: |
-      [Match]
-      Name=po0
-
-      [Link]
-      MACAddress={{.host.interfaces.first.mac}}
-
-      [Network]
-      DHCP=ipv4
-      BindCarrier={{.host.interfaces.first.identifier}} {{.host.interfaces.second.identifier}}
-  - path: /etc/systemd/network/{{.host.interfaces.first.identifier}}.network
-    permissions: 0644
-    owner: root
-    content: |
-      [Match]
-      Name={{.host.interfaces.first.identifier}}
-
-      [Network]
-      Bond=po0
-  - path: /etc/systemd/network/{{.host.interfaces.second.identifier}}.network
-    permissions: 0644
-    owner: root
-    content: |
-      [Match]
-      Name={{.host.interfaces.second.identifier}}
-
-      [Network]
-      Bond=po0
-{{ end }}
-
-
-
-
